const CATEGORY_MAP: Record<string, string> = {
  // Sports
  NBA: "Sports", NFL: "Sports", NHL: "Sports", MLB: "Sports",
  UFC: "Sports", FIFA: "Sports", "Premier League": "Sports",
  "Champions League": "Sports", "World Cup": "Sports",
  Lakers: "Sports", Warriors: "Sports", Yankees: "Sports",
  Celtics: "Sports", Dodgers: "Sports", Chiefs: "Sports",
  Eagles: "Sports", Cowboys: "Sports", Knicks: "Sports",
  "49ers": "Sports", Mets: "Sports", Braves: "Sports",
  Steelers: "Sports", Bills: "Sports", Packers: "Sports",
  NBAPlayoffs: "Sports", "March Madness": "Sports",
  "Super Bowl": "Sports", "World Series": "Sports",
  "Stanley Cup": "Sports", Olympics: "Sports",
  "Luka Doncic": "Sports", LeBron: "Sports", Curry: "Sports",
  Messi: "Sports", Ronaldo: "Sports", "Shohei Ohtani": "Sports",
  Mahomes: "Sports", "Aaron Judge": "Sports",
  "Jalen Brunson": "Sports", "Lamar Jackson": "Sports",
  "Patrick Mahomes": "Sports", "Saquon Barkley": "Sports",
  "Victor Wembanyama": "Sports", Wemby: "Sports",
  "Caitlin Clark": "Sports", WNBA: "Sports",
  Arsenal: "Sports", "Man City": "Sports", "Man United": "Sports",
  Liverpool: "Sports", Barcelona: "Sports", "Real Madrid": "Sports",
  "Serie A": "Sports", "La Liga": "Sports", Bundesliga: "Sports",
  F1: "Sports", "Formula 1": "Sports", NASCAR: "Sports",
  Tennis: "Sports", "US Open": "Sports", Wimbledon: "Sports",
  Boxing: "Sports", MMA: "Sports",

  // Tech
  AI: "Tech", ChatGPT: "Tech", OpenAI: "Tech", Google: "Tech",
  Apple: "Tech", NVIDIA: "Tech", Tesla: "Tech", Microsoft: "Tech",
  "GPT-5": "Tech", Claude: "Tech", Gemini: "Tech", Anthropic: "Tech",
  Meta: "Tech", Amazon: "Tech", Samsung: "Tech", iPhone: "Tech",
  Android: "Tech", iPad: "Tech", MacBook: "Tech",
  "Elon Musk": "Tech", "Tim Cook": "Tech", "Sam Altman": "Tech",
  "Mark Zuckerberg": "Tech", "Satya Nadella": "Tech",
  Copilot: "Tech", GitHub: "Tech", "VS Code": "Tech",
  Midjourney: "Tech", "Stable Diffusion": "Tech", Sora: "Tech",
  "Vision Pro": "Tech", VR: "Tech", AR: "Tech",
  Robotics: "Tech", Neuralink: "Tech", SpaceX: "Tech",
  Starship: "Tech", Starlink: "Tech",
  TikTok: "Tech", Instagram: "Tech", Threads: "Tech",
  YouTube: "Tech", Snapchat: "Tech", Reddit: "Tech",
  "X Premium": "Tech", Twitter: "Tech",
  Cybersecurity: "Tech", Hacking: "Tech",
  Pixel: "Tech", OnePlus: "Tech",
  AWS: "Tech", Azure: "Tech", "Google Cloud": "Tech",

  // Crypto
  Bitcoin: "Crypto", BTC: "Crypto", Ethereum: "Crypto", ETH: "Crypto",
  Crypto: "Crypto", Solana: "Crypto", SOL: "Crypto",
  Dogecoin: "Crypto", DOGE: "Crypto", XRP: "Crypto",
  Cardano: "Crypto", ADA: "Crypto", Polygon: "Crypto",
  Avalanche: "Crypto", AVAX: "Crypto",
  NFT: "Crypto", NFTs: "Crypto", DeFi: "Crypto",
  Binance: "Crypto", Coinbase: "Crypto",
  "SEC Crypto": "Crypto", "Bitcoin ETF": "Crypto",
  Altcoin: "Crypto", Memecoin: "Crypto",
  Web3: "Crypto", Blockchain: "Crypto",

  // Politics
  Congress: "Politics", Senate: "Politics", SCOTUS: "Politics",
  "Supreme Court": "Politics", "White House": "Politics",
  Democrat: "Politics", Republican: "Politics", Election: "Politics",
  Biden: "Politics", Trump: "Politics", DeSantis: "Politics",
  "AOC": "Politics", Pelosi: "Politics", McConnell: "Politics",
  Governor: "Politics", Mayor: "Politics",
  "Executive Order": "Politics", Impeach: "Politics",
  NATO: "Politics", UN: "Politics", EU: "Politics",
  Ukraine: "Politics", Russia: "Politics", China: "Politics",
  Iran: "Politics", Israel: "Politics", Palestine: "Politics",
  Gaza: "Politics", "Middle East": "Politics",
  Immigration: "Politics", Border: "Politics",
  "Gun Control": "Politics", Abortion: "Politics",
  "2nd Amendment": "Politics",
  "Project 2025": "Politics",
  Indictment: "Politics", FBI: "Politics", DOJ: "Politics",
  "Jan 6": "Politics", Insurrection: "Politics",

  // Finance
  "Fed Rate": "Finance", "Interest Rate": "Finance",
  "Stock Market": "Finance", "Wall Street": "Finance",
  "S&P 500": "Finance", "S&P": "Finance",
  Nasdaq: "Finance", "Dow Jones": "Finance",
  Recession: "Finance", Inflation: "Finance",
  "Federal Reserve": "Finance", "Jerome Powell": "Finance",
  IPO: "Finance", Earnings: "Finance", Revenue: "Finance",
  Dividend: "Finance", "Market Cap": "Finance",
  "Bank of America": "Finance", "JP Morgan": "Finance",
  "Goldman Sachs": "Finance", "Morgan Stanley": "Finance",
  "Wells Fargo": "Finance", Citibank: "Finance",
  "Housing Market": "Finance", Mortgage: "Finance",
  GDP: "Finance", "Jobs Report": "Finance", Unemployment: "Finance",
  Tariff: "Finance", Tariffs: "Finance",
  "Trade War": "Finance",

  // Culture
  "Beyoncé": "Culture", "Taylor Swift": "Culture", Drake: "Culture",
  "Travis Scott": "Culture", Rihanna: "Culture", Kanye: "Culture",
  "Bad Bunny": "Culture", Kendrick: "Culture", "Nicki Minaj": "Culture",
  "Doja Cat": "Culture", "Ice Spice": "Culture", SZA: "Culture",
  "Tyler the Creator": "Culture", "21 Savage": "Culture",
  Grammys: "Culture", "Met Gala": "Culture", Oscars: "Culture",
  "Golden Globes": "Culture", Emmys: "Culture",
  Coachella: "Culture", "Rolling Loud": "Culture",
  "Kim Kardashian": "Culture", Kardashian: "Culture",
  "MrBeast": "Culture", KSI: "Culture", Logan: "Culture",
  Viral: "Culture", Meme: "Culture", "Stan Twitter": "Culture",
  Fashion: "Culture", Streetwear: "Culture",

  // Entertainment
  Netflix: "Entertainment", Disney: "Entertainment",
  HBO: "Entertainment", Hulu: "Entertainment",
  "Amazon Prime": "Entertainment", "Apple TV": "Entertainment",
  Marvel: "Entertainment", "DC Comics": "Entertainment",
  "Star Wars": "Entertainment", Batman: "Entertainment",
  Superman: "Entertainment", "Spider-Man": "Entertainment",
  Deadpool: "Entertainment", Avengers: "Entertainment",
  "Stranger Things": "Entertainment", "The Bear": "Entertainment",
  Euphoria: "Entertainment", "Squid Game": "Entertainment",
  Anime: "Entertainment", Manga: "Entertainment",
  "One Piece": "Entertainment", "Jujutsu Kaisen": "Entertainment",
  "Dragon Ball": "Entertainment", Naruto: "Entertainment",
  "Attack on Titan": "Entertainment",
  "Box Office": "Entertainment", Trailer: "Entertainment",
  Barbie: "Entertainment", Oppenheimer: "Entertainment",
  "K-pop": "Entertainment", BTS: "Entertainment",
  BLACKPINK: "Entertainment", Stray: "Entertainment",

  // News
  Breaking: "News", "#Breaking": "News",
  BREAKING: "News", RIP: "News", "Rest in Peace": "News",
  "Mass Shooting": "News", Shooting: "News",
  Earthquake: "News", Hurricane: "News", Tornado: "News",
  Wildfire: "News", Flood: "News", Tsunami: "News",
  "Missing Person": "News", Amber: "News",
  Recall: "News", Investigation: "News",
  Protest: "News", Riot: "News",
  "Train Derailment": "News", Crash: "News",
  Hostage: "News", Bombing: "News",

  // Science
  Climate: "Science", "Climate Change": "Science",
  NASA: "Science", Space: "Science", Mars: "Science",
  Moon: "Science", Eclipse: "Science", Asteroid: "Science",
  Vaccine: "Science", "Bird Flu": "Science", Pandemic: "Science",
  "Global Warming": "Science", "Carbon Emissions": "Science",
  "Renewable Energy": "Science", Solar: "Science",
  "Electric Vehicle": "Science", EV: "Science",
  "James Webb": "Science", "Black Hole": "Science",

  // Games
  Wordle: "Games", "Call of Duty": "Games", COD: "Games",
  Fortnite: "Games", Minecraft: "Games", Roblox: "Games",
  PlayStation: "Games", PS5: "Games", Xbox: "Games",
  Nintendo: "Games", Switch: "Games", "Mario": "Games",
  Zelda: "Games", Pokemon: "Games", "Elden Ring": "Games",
  GTA: "Games", "GTA 6": "Games", "GTA VI": "Games",
  Valorant: "Games", "League of Legends": "Games", LoL: "Games",
  Apex: "Games", Overwatch: "Games",
  Palworld: "Games", Helldivers: "Games",
  Steam: "Games", "Game Pass": "Games",
  Esports: "Games", Twitch: "Games",

  // Health
  "Mental Health": "Health", "#MentalHealth": "Health",
  Depression: "Health", Anxiety: "Health",
  "Weight Loss": "Health", Ozempic: "Health",
  Cancer: "Health", "Heart Disease": "Health",
  Diabetes: "Health", Alzheimer: "Health",
  "Drug Overdose": "Health", Fentanyl: "Health",
  "Health Care": "Health", Medicare: "Health",
  Medicaid: "Health", "ACA": "Health",
  Fitness: "Health", Gym: "Health", Wellness: "Health",
  Nutrition: "Health", Diet: "Health",
  COVID: "Health", "Long COVID": "Health",
  WHO: "Health",
};

export function classifyTrend(trendName: string): string {
  const lower = trendName.toLowerCase().replace(/^#/, "");

  for (const [keyword, category] of Object.entries(CATEGORY_MAP)) {
    const keyLower = keyword.toLowerCase().replace(/^#/, "");
    if (lower === keyLower || lower.includes(keyLower)) {
      return category;
    }
  }

  return "Trending";
}

export const CATEGORY_COLORS: Record<string, string> = {
  Tech: "#A78BFA",
  Politics: "#FB923C",
  Sports: "#34D399",
  Crypto: "#FBBF24",
  Culture: "#F472B6",
  Finance: "#60A5FA",
  News: "#EF4444",
  Entertainment: "#EC4899",
  Science: "#22D3EE",
  Games: "#A3E635",
  Health: "#6EE7B7",
  Trending: "#888888",
};
